// src/app/layout.js

import React from 'react';
import { BrowserRouter } from 'react-router-dom';
import Router from '../components/router';

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({ children }) {
 return (
    <BrowserRouter>
      <html lang="en">
        <body>{children}</body>
      </html>
    </BrowserRouter>
  )
}
