// src/app/page.js

import React from 'react';
import { BrowserRouter } from 'react-router-dom';
import Router from '../components/router';

export default function Home() {
  return (
    <BrowserRouter>
      <Router />
    </BrowserRouter>
  );
}

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
};
